In [ ]:
import torch
from torch.nn import MSELoss, L1Loss

## Setup

In [ ]:
xs = torch.arange(start=-10, end=10, step=0.2)
ys = torch.load('ys.pkl') ## same as debugYs in app

In [ ]:
def mk_quad(a,b):
    return lambda x: a*torch.pow(x,2)+b*x

In [ ]:
ab = torch.tensor([1.,1.], requires_grad=True)
quad = mk_quad(*ab)

## MAE

In [ ]:
ab.grad = None
critic = L1Loss()
pred_ys = quad(xs)

In [ ]:
loss = critic(pred_ys, ys)
loss

tensor(66.9172, grad_fn=<L1LossBackward0>)

In [ ]:
loss.backward()
ab.grad

tensor([-33.2632,   0.0440])

In [ ]:
gradients_magnitude = torch.norm(ab.grad)
gradients_magnitude

tensor(33.2632)

## MSE

In [ ]:
critic = MSELoss()

In [ ]:
ab.grad = None
pred_ys = quad(xs)
loss = critic(pred_ys, ys)
loss

tensor(8016.4155, grad_fn=<MseLossBackward0>)

In [ ]:
loss.backward()
ab.grad

tensor([-7910.7666,   -15.1460])

In [ ]:
gradients_magnitude = torch.norm(ab.grad)
gradients_magnitude

tensor(7910.7808)

## RMSE

In [ ]:
critic = MSELoss() ## root applied at loss

In [ ]:
ab.grad = None
pred_ys = quad(xs)

In [ ]:
loss = torch.sqrt(critic(pred_ys, ys))
loss

tensor(89.5344, grad_fn=<SqrtBackward0>)

In [ ]:
loss.backward()
ab.grad

tensor([-44.1772,  -0.0846])

In [ ]:
gradients_magnitude = torch.norm(ab.grad)
gradients_magnitude

tensor(44.1773)